name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on every push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Docusaurus site
      - name: Build Docusaurus site
        run: npm run build

      # 5️⃣ Deploy to GitHub Pages (safe latest stable tag)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          user_name: "shivamp9381"
          user_email: "shivamp9381@users.noreply.github.com"
