name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Docusaurus site
      - name: Build Docusaurus site
        run: npm run build

      # 5️⃣ Configure Git for deployment
      - name: Setup Git user
        run: |
          git config --global user.name "shivamp9381"
          git config --global user.email "shivamp9381@users.noreply.github.com"

      # 6️⃣ Deploy using gh-pages CLI
      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d build -b gh-pages -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shivamp9381/javajoltjournal.git
